### ISSUE TITLE
When i use it in 4.24 and vs2017,i get a error

### ISSUE THREAD

**Issue by 17702513221** [bakjos/FFMPEGMedia#11]
![EMP1OEB7`2PYPV33PV2XL%D](https://user-images.githubusercontent.com/40785359/89404060-eef87200-d74b-11ea-9a24-9cb38e7bccc3.png)
Can you help me

**Comment by bakjos** [comment]
@17702513221 Does it work if you use this branch https://github.com/bakjos/FFMPEGMedia/tree/feature/android_build?

**Comment by 17702513221** [comment]
![7PUONK(VG4{A9`~S@$@@UN1](https://user-images.githubusercontent.com/40785359/89478909-0d01b900-d7c4-11ea-99a2-3c54a3c0e75c.png)
I git a same error in android_build
