### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 499418465** [bakjos/FFMPEGMedia#12]
I am using UE4.22
When I turn on RTSP/RTMP, the network is in an unstable/open multiple video, close media crash occurs.
<img width="1119" alt="641129d7dc94bdd63c8c1c8d2afe915" src="https://user-images.githubusercontent.com/20896330/89488009-78a25100-d7d9-11ea-9455-1b2beaa4a5bb.png">

**Comment by 499418465** [comment]
I use VS2017.

**Comment by giomerlin** [comment]
@499418465 I pushed a couple of changes, can you check if it's working now?

**Comment by 499418465** [comment]
Problem solved！ thanks
