### ISSUE TITLE
How Can i Install it? I am new newbie

### ISSUE THREAD

**Issue by santiagodml** [bakjos/FFMPEGMedia#16]
Excuse if my question is too basic, buy I dont know how to install this plug in.
I Don't know how to do it. Putting it in the plugins folder and activating it in the editor produce errors, with 4.23, but also with 4.18 and 4.19.

Apreciate you guidance

**Comment by bakjos** [comment]
@santiagodml I haven't tried running  a 4.19 version using the latest commit, it may be due some dependencies, what error are you getting when the plugin is compiled?

**Comment by santiagodml** [comment]
I think I dont know how to compile it. Just copy the whole folder to unreal/plugins. Unreal try to compile but ask to do it manually and i dont know how. Try to open visual studio and "rebuild" the folder but doesn't work for me

**Comment by bakjos** [comment]
@santiagodml  When you right click on your project, you can generate the visual studio solution for the project, once you open it and try to build should show you the error on the output window, I just test the current version with UE 4.25, so may be was something added/deleted between the versions

**Comment by santiagodml** [comment]
I think there are some missing files or I am doing something wrong: 

Error	C1083	No se puede abrir el archivo incluir: 'WindowsHWrapper.h': No such file or directory	HostProject	C:\Users\Santiago\Desktop\HostProject\Plugins\FFMPEGMedia\Source\FFMPEGMediaFactory\Private\FFMPEGMediaFactoryModule.cpp	17	

Error	C1083	No se puede abrir el archivo incluir: 'ScopeLock.h': No such file or directory	HostProject	C:\Users\Santiago\Desktop\HostProject\Plugins\FFMPEGMedia\Source\FFMPEGMedia\Private\FFMPEG\CondWait.h	4

**Comment by santiagodml** [comment]
I tried adding those files from the engine buy had mode errors
WindowsHWrapper.h
ScopeLock.h
GenericPlatformProcess.h
IPluginManager.h
RunnableThread.h
Runnable.h

If I try with 4.25 it will work ?

**Comment by bakjos** [comment]
@santiagodml All those files are part of the Core engine, so it might be something misconfigured, I suggest clear all the binary, build and Intermediate folders from the root project dir and all the plugins, update your project to the 4.25 version (using the right click option on the explorer) and then regenerate the solution (from the context menu as well)

**Comment by santiagodml** [comment]
@bakjos recien me doy cuenta que eres de colombia. Quiza puedo explicarme mejor en castellano :)

Lo que hice fue bajar la version 4.25, crear un proyecto nuevo con C++, abri el proyecto con visual studio, lo compile. 
Cerre visual studio, cree una carpeta llamada Plugins y coloque dentro el contenido del plugin descargado desde aqui. 
Abri nuevamente el proyecto con visual studio, coloque compilar y me die el mismo error de antes, que faltaban esos archivos. 
Quiza tengo que hacer alguna configuracion adicional. 
La verdad es que si ejecuto el proyecto de unreal esto se hace automaticamente pero falla tambien. 
Por si estaba haciendo algo mas segui los pasos de como compilar un plugin segun [este video](https://www.youtube.com/watch?v=WtfLfYY_k2Y&t=214s), que lo hace desde la consola, pero el resultado es exactamente el mismo, da el mismo error. 

Quiza estoy haciendo algo mas yo pero no se que mas puedo probar

**Comment by bakjos** [comment]
@santiagodml En teoría lo que hiciste debería funcionar, por lo que veo estás usando windows, visual studio 2017 y UE 4.25, verdad?, la ruta del plugin debería ser algo como ${ROOT_PROJECT}/Plugins/FFMPEGMedia/FFMPEGMedia.uplugin, cuando lanzas el proyecto te dice que deberías recompilarlo y falla cuando lo recompila ? Puede ser también que no hayas instalado el sdk de windows, https://docs.unrealengine.com/en-US/Programming/Development/VisualStudioSetup/index.html. Una vez tengas instalada la configuración de game development with c++, puedes regenerar el proyecto (haces click derecho en el .uproject y seleccionas la opción de generate visual studio project)

**Comment by santiagodml** [comment]
Gracias @bakjos por tomarte el tiempo y molestia en responder mis mensajes. 

Te queria comentar que hice todo lo que me dijiste, la unica diferencia es que estoy usando vs2019, pero imagino que no deberia haber diferencia. 
segui todos los pasos de la guia de configuracion de visual studio pero tampoco habia nada mal. 

Volvi a agregar uno a uno los archivos que al compilar no encontraba. Quiza haya alguna forma de indicar que lea eso directamente de la carpeta de UE, aunque ya esta UE4 en dependencias.

No se si aporta, pero el error tras agregar los archivos es este: 
2>  C:/Users/Santiago/Desktop/FFM/Plugins/FFMPEGMedia-master/Source/FFMPEGMedia/Private/Player/FFMPEGMediaTracks.cpp(1935): note: No existe un contexto en el que sea posible realizar esta conversi�n

**Comment by santiagodml** [comment]
Y cuando no le pongo los archivos manualmente el resultado es este: 

`1>------ Operación Compilar omitida: proyecto: UE4, configuración: BuiltWithUnrealBuildTool Win32 ------
1>Proyecto no seleccionado para compilarse para esta configuración de solución 
2>------ Operación Compilar iniciada: proyecto: FFM, configuración: Shipping Win32 ------
2>Creating makefile for FFM (no existing makefile)
2>... LibrariesPath -> C:\Users\Santiago\Desktop\FFM\Plugins\FFMPEGMedia\ThirdParty\ffmpeg\lib\vs\Win32
2>Parsing headers for FFM
2>  Running UnrealHeaderTool "C:\Users\Santiago\Desktop\FFM\FFM.uproject" "C:\Users\Santiago\Desktop\FFM\Intermediate\Build\Win32\FFM\Shipping\FFM.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
2>Reflection code generated for FFM in 4,3824039 seconds
2>Building FFM...
2>Using Visual Studio 2019 14.26.28806 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
2>Building 15 actions with 12 processes...
2>  [1/15] Default.rc2
2>  [2/15] SharedPCH.CoreUObject.NonOptimized.ShadowErrors.cpp
2>  [3/15] Module.FFMPEGMediaFactory.cpp
2>C:/Users/Santiago/Desktop/FFM/Plugins/FFMPEGMedia/Source/FFMPEGMediaFactory/Private/FFMPEGMediaFactoryModule.cpp(17): fatal error C1083: No se puede abrir el archivo incluir: 'WindowsHWrapper.h': No such file or directory
2>  [4/15] Module.FFMPEGMediaFactory.gen.cpp
2>  [5/15] SharedPCH.Engine.ShadowErrors.cpp
2>  [6/15] SharedPCH.Engine.Exceptions.ShadowErrors.cpp
2>  [7/15] Module.FFMPEGMedia.cpp
2>C:\Users\Santiago\Desktop\FFM\Plugins\FFMPEGMedia\Source\FFMPEGMedia\Private\FFMPEG\CondWait.h(4): fatal error C1083: No se puede abrir el archivo incluir: 'ScopeLock.h': No such file or directory
2>  [8/15] FFM.cpp
2>  [9/15] FFM.init.gen.cpp
2>  [10/15] FFMGameMode.gen.cpp
2>  [11/15] FFMGameMode.cpp
2>  [12/15] FFMCharacter.gen.cpp
2>  [13/15] FFMCharacter.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(46,5): error MSB3075: El comando "chcp 65001 >NUL && C:\Unreal\UE_4.24\Engine\Build\BatchFiles\Build.bat FFM Win32 Shipping -Project="C:\Users\Santiago\Desktop\FFM\FFM.uproject" -WaitMutex -FromMsBuild" salió con el código 5. Compruebe que tiene derechos suficientes para ejecutar este comando.
2>Compilación del proyecto "FFM.vcxproj" terminada -- ERROR.
========== Compilar: 0 correctos, 1 incorrectos, 0 actualizados, 1 omitidos ==========`

**Comment by bakjos** [comment]
@santiagodml cómo agregaste los archivos ? cuando se genera el proyecto, se deberían incluir todos los archivos de los plugins, así que mi sospecha es que el proyecto no lo has generado de nuevo, así que lo que puedes hacer es borrar el .sln, los directorios intermediate tanto de los plugins como del raíz y volver a generar el proyecto, no deberías agregar los archivos de forma manual

**Comment by santiagodml** [comment]
@bakjos borre los intermediate y el .sln, los genere de nuevo, pero siempre me sale que le falta WindowsHWrapper.h y ScopeLock.h . 

Lo probé con un proyecto nuevo vacío y pasa lo mismo. Una lastima, quería mucho ver si este plugin funcionaba mejor que el media framework

Gracias por tu ayuda, saludos

**Comment by santiagodml** [comment]
@bakjos 
Descargué 2 plugins cualquiera solo para probar y ambos compilaron sin errores y los pude usar en UE4
Quizá el problema sea otro

**Comment by santiagodml** [comment]
@bakjos por si sirve a alguien más finalmente pude compilarlo y usarlo. 

Lo que tuve que hacer fue a medida que iba pidiendome los include, quitarlos agregandole // por delante
Uno lo necesitaba para continuar: IPluginManager.h asi que ese lo busque en la carpeta de UE y lo pegue aqui: FFMPEGMedia-master\Source\FFMPEGMedia\Private

Con eso compilo sin errores, lo pude agregar en el editor y usarlo normalmente.  No entiendo que paso, pero ahora funciona. Aparece en el desplegable de "player overrides".

Gracias por el trabajo! saludos

**Comment by bakjos** [comment]
@santiagodml En el build.cs de tu proyecto cuales módulos están incluídos en PublicDependencyModules?

**Comment by santiagodml** [comment]
Use un proyecto nuevo y vacio, el build.cs esta asi:

using UnrealBuildTool;

public class MyProjectTEST : ModuleRules
{
	public MyProjectTEST(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
	
		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore" });

		PrivateDependencyModuleNames.AddRange(new string[] {  });

		// Uncomment if you are using Slate UI
		// PrivateDependencyModuleNames.AddRange(new string[] { "Slate", "SlateCore" });
		
		// Uncomment if you are using online features
		// PrivateDependencyModuleNames.Add("OnlineSubsystem");

		// To include OnlineSubsystemSteam, add it to the plugins section in your uproject file with the Enabled attribute set to true
	}
}

**Comment by bakjos** [comment]
@santiagodml puedes borrar el archivo de la carpeta prívate y cambiar el include a Interfaces/IPluginManager.h acá ? https://github.com/bakjos/FFMPEGMedia/blob/3c264fdc86cb4bb69592d519c82b6d4aa4e1c9ef/Source/FFMPEGMedia/Private/FFMPEGMediaModule.cpp#L10

**Comment by santiagodml** [comment]
Si lo saco me aparece :
 No se puede abrir el archivo incluir: 'IPluginManager.h': No such file or directory

**Comment by bakjos** [comment]
@bakjos Pero cambiaste el include de #include "IPluginManager.h" a #include "Interfaces/IPluginManager.h"?

**Comment by bakjos** [comment]
@santiagodml Acabo de subir el cambio, así que puedes actualizar el proyecto también y quitar el Ipluginmanager.h del directorio a ver si con eso lo soluciona, lo raro es que en XCode y VS 2019 funciona bien sin el cambio adicional

**Comment by santiagodml** [comment]
En esta ultima version me sigue fallando y sigue sin encontrar la misma lista de includes: 

WindowsHWrapper.h
ScopeLock.h
GenericPlatformProcess.h
IPluginManager.h
RunnableThread.h
Runnable.h

Solo que ahora, si borro los includes que hacen referencia a los archivos de más arriba me compila sin la necesidad de agregar el archivo IPluginManager.h ni ningun otro

**Comment by kimba23** [comment]
Hello. I have the same exact error. Yo tambien hablo espanol y releyendo esto veo que tengo el mismo error, alguna sugerencia?

**Comment by thomasvanta** [comment]
Buenas!
El mismo error:


Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ScopeLock.h': No such file or directory	TestVLC_Player	V:\Code\Unreal\TestVLC_Player\Plugins\FFMPEGMedia\Source\FFMPEGMedia\Private\FFMPEG\CondWait.h	4	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'WindowsHWrapper.h': No such file or directory	TestVLC_Player	V:\Code\Unreal\TestVLC_Player\Plugins\FFMPEGMedia\Source\FFMPEGMediaFactory\Private\FFMPEGMediaFactoryModule.cpp	17	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Program Files\Epic Games\UE_4.25\Engine\Build\BatchFiles\Build.bat" TestVLC_PlayerEditor Win64 Development -Project="V:\Code\Unreal\TestVLC_Player\TestVLC_Player.uproject" -WaitMutex -FromMsBuild" exited with code 6.	TestVLC_Player	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	46	


Estoy en UE 4.25.4 y VS 19

**Comment by bakjos** [comment]
@kimba23 @thomasvanta I just had time today to take a look on this issue, but I haven't been able to reproduce the issue, it might be due my project settings, can you send me your uproject settings and the .Target.cs files?

**Comment by thezulk** [comment]
I had the same issue.
It seems this plugin isn't working with build settings version 2.
Solved it by creating a new project, addad a C++ class and changed BuildSettingsVersion.V2 to BuildSettingsVersion.V1 in the .target.cs files.
It then compiled without a problem.
I could then copy the compiled plugin to my primary project.

**Comment by bakjos** [comment]
The latest master version is compatible with the  BuildSettingsVersion.V2, thanks @thezulk for giving me a hint about the error
