### ISSUE TITLE
How to specify TCP protocol?

### ISSUE THREAD

**Issue by 499418465** [bakjos/FFMPEGMedia#18]
How to specify TCP protocol?
![tcp](https://user-images.githubusercontent.com/20896330/93970098-ee6d7680-fd9f-11ea-8d61-a5b177193c9c.jpg)

**Comment by 499418465** [comment]
Can you help me?

**Comment by 499418465** [comment]
I use UE4.24,vs2019.    Is there an error because of the TCP link?

**Comment by bakjos** [comment]
@499418465  You can change what protocol you want to use from the plugin settings, inside the project settings. by default it will try UDP first and if it fails it will switch to TCP, seeing the logs you include, the server is responding with an error 500, so I would say the issue is not the protocol but the server itself

**Comment by 499418465** [comment]
This problem I query should be a TCP protocol problem.Which is the project setting?
![1600867723(1)](https://user-images.githubusercontent.com/20896330/94018956-c9025c00-fde3-11ea-85d9-67e65944a0d5.jpg)

**Comment by 499418465** [comment]
This problem I query should be a TCP protocol problem.Which is the project setting?
![1600867723(1)](https://user-images.githubusercontent.com/20896330/94018956-c9025c00-fde3-11ea-85d9-67e65944a0d5.jpg)

**Comment by 499418465** [comment]
This problem I query should be a TCP protocol problem.Which is the project setting?
![1600867723(1)](https://user-images.githubusercontent.com/20896330/94018956-c9025c00-fde3-11ea-85d9-67e65944a0d5.jpg)

**Comment by 499418465** [comment]
Here's what I found
https://medium.com/androvideo/ffmpeg-udp-timeout-retrying-with-tcp-8def8a948cee

**Comment by 499418465** [comment]
@bakjos

**Comment by 499418465** [comment]
And VLC can turn it on.

**Comment by bakjos** [comment]
@499418465 I think you don't have the latest version, there's another new option named Rstp Transport. But I don't think that's the issue, in the medium article the error is 405, in your logs is sending an error 500, so I think the issue is the server

**Comment by 499418465** [comment]
@bakjos Try the new version. And why can VLC turn it on?

**Comment by 499418465** [comment]
I will give you feedback on the new version later

**Comment by 499418465** [comment]
@bakjos   New version of TCP can run! Thank you!     
However, the new version header file is missing, I added.
